### ISSUE TITLE
Why not help improve react-router?

### ISSUE THREAD

**Issue by mjackson** [ArnaudRinquin/redux-reroute#1]
If you've got issues with React Router, we'd love to help you solve them. There's also the [redux-router](https://github.com/rackt/redux-router) project which provides bindings between React Router and redux. We would welcome your contributions :)

**Comment by ArnaudRinquin** [comment]
The main reason why I discarded contributing to `redux-router` is that there is a paradigm shift.

`redux-router`, by having <Router> at the top of everything still handles location as the only dimension in routing logic, leaving no non-hacky room to integrate other logic (auth, data dependency, etc...).

I just [pushed an update](https://github.com/ArnaudRinquin/reroute/commit/a70f6bc4011e15d5b1bb432a63b0a03e3a407e99) to the [Why no `redux-router`](https://github.com/ArnaudRinquin/reroute#why-not-redux-router) section.

I really don't see how to retrofit that into `redux-router`.

Maybe by advertising alternatives to using `<Router>` but leveraging the `reducer` it uses and providing the component selectors `reroute` provides.

What to you think?

**Comment by mjackson** [comment]
> The main reason why I discarded contributing to redux-router is that there is a paradigm shift.

I can respect that, but I think you may believe that things in redux-router are more set in stone than they actually are :)

If you have better ideas than what we've already got over there (which is highly probable), by all means, change our API in a PR. Change everything. Become the main project maintainer and shift the paradigm :) At least then you won't be working in isolation and have to convince everybody to use your thing instead of the official redux bindings for react router. And you'll have a community of people who are already working hard at solving these same problems to collaborate with.

**Comment by ArnaudRinquin** [comment]
I think you are right about `react-router` / `redux-router` traction and community being really helpful.

The main reason behind `redux-reroute` is to handle a (not-so) specific use case, which I think it does. I definitely needed to builded it to understand the ropes of routing and design the API we would like to use.

Now I think I've got a really good idea of what a non-location-only router needs and could probably port it to `re[act|dux]-router`.

In he mean time, this project can live ; I'll deprecate it if and when such use cases can be handled using "the popular one".

Thanks for the feedback :+1:

**Comment by mjackson** [comment]
> I definitely needed to builded it to understand the ropes of routing and design the API we would like to use.

I definitely understand that. I've done the same thing before, many times.

If the time comes that you think you'd like to contribute to redux/react-router, we'll happily welcome you :)
