### ISSUE TITLE
what do you think about redux-tiny-router?

### ISSUE THREAD

**Issue by gut4** [ArnaudRinquin/redux-reroute#3]
https://github.com/Agamennon/redux-tiny-router

**Comment by ArnaudRinquin** [comment]
I think both projects come from the same observation:

>  stop using the router as a controller... its just state!

We're trying to solve the same problem in a very similar way: put location data (route pattern, url params etc...) in the application state so you can write your routing logic however you like.

From what I've seen, `redux-tiny-router` has a bigger boilerplate and I an not fan of the API but we basically do the same thing.

In the example it uses a `switch-case` to pick the right component:

```js
@connect((state ) => {  
    return {
        router:state.router
     }
})
const Comp = React.createClass({
  render() {
    switch (this.props.router.path) {
        case '/':
            return <Home/>;
        case '/other':
            return <Other/>
        default:
            return <NotFound/>;
    }
  }
});
```

This is very similar to my minimalistic example.

A nice thing with `reroute` is the `createComponentSelector` helper, that will basically do the same but as a `@connect` selector so you don't have to write this `switch-case` and can combine it with any other selector using [`reselect`](https://github.com/rackt/reselect)

Something I like is that it puts more data in the app state, like the full path, query strings, and few more things, while `reroute` only puts `matchedRoute` (the pattern) and `urlParams` (which are both taken from the path and query string). I think I should add that.

**Comment by ArnaudRinquin** [comment]
Another thing I think I need to add is the universal app compatibility. I have a idea on how to do that, it's only a matter of time.
